# Generated by Django 3.1.4 on 2021-01-06 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('isbn', models.CharField(max_length=10)),
                ('original_publication_year', models.FloatField()),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('image_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AuthorToBook',
            fields=[
                ('id',
                 models.AutoField(auto_created=True,
                                  primary_key=True,
                                  serialize=False,
                                  verbose_name='ID')),
                ('author_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='books.author')),
                ('book_id',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='books.book')),
            ],
        ),
    ]
