name: yabr
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - scikit-surprise
  - pip:
      - django==3.1.4
      - pre-commit
      - yapf
      - isort
      - djangorestframework
